apiVersion: v2
appVersion: 2.0.44
description: dnscrypt-proxy for Kubernetes
icon: https://github.com/DNSCrypt/dnscrypt-proxy/blob/master/logo.png
keywords:
  - dnscrypt
maintainers:
  - email: antoine@tanzil.li
    name: Antoine TANZILLI
name: dnscrypt-proxy
sources:
  - https://github.com/Tailzip/dnscrypt-proxy-helm-chart
type: application
version: 0.1.0
